name: Build Geode Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build clang

      - name: Clone Geode
        run: |
          git clone https://github.com/geode-sdk/geode.git
          cd geode
          git submodule update --init --recursive

      - name: Build Mod
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DGEODE_SDK_PATH=$GITHUB_WORKSPACE/geode
          ninja

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/*.geode
